/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ReactComponents: typeof import('./src/components/reactComponents.vue')['default']
    SuspenseWithError: typeof import('./src/components/suspenseWithError.vue')['default']
  }
}
